import { storage } from '../storage/local';
import { getCurrentBrand } from '../domain/brand';
import { getBrandSoul, SOUL_SCHEMA } from './soul';

/**
 * Brand book export — the semantic assets (soul + top concepts) rendered as
 * a standalone printable HTML file. The first time the brand's invisible
 * DNA becomes something you can hand to a dealer or a new team member.
 */

const esc = (s: string) =>
    s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

export async function exportBrandBook(): Promise<void> {
    const brand = await getCurrentBrand();
    const soul = await getBrandSoul();
    const elements = (await storage.listElements()).filter(e => e.enabled);
    const top = [...elements].sort((a, b) => b.weight - a.weight).slice(0, 12);
    const labelOf = (key: string) => SOUL_SCHEMA.find(s => s.key === key)?.label ?? key;

    const axisBlock = (axis: 'narrative' | 'sensation' | 'viewing', title: string) => {
        const fields = (soul?.fields ?? []).filter(f => f.axis === axis && f.value.trim());
        if (fields.length === 0) return '';
        return `<section><h2>${title}</h2>${fields.map(f => `
            <div class="field${f.locked ? ' locked' : ''}">
                <h3>${esc(labelOf(f.key))}${f.locked ? ' <span class="badge">RED-LINE</span>' : ''}</h3>
                <p>${esc(f.value)}</p>
            </div>`).join('')}</section>`;
    };

    const lensTitle: Record<string, string> = { visual: 'Visual', feeling: 'Feeling', communication: 'Communication' };
    const conceptsBlock = top.length === 0 ? '' : `<section><h2>Concept Library — Top ${top.length}</h2>
        ${top.map(e => `
        <div class="concept">
            <h3>“${esc(e.concept)}” <span class="lens">${lensTitle[e.type] ?? e.type} · w${e.weight.toFixed(1)}</span></h3>
            ${e.analysis ? `<p class="analysis">${esc(e.analysis)}</p>` : ''}
            <p class="manifest">↳ ${esc(e.description)}</p>
        </div>`).join('')}</section>`;

    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${esc(brand.name)} — Brand Book</title>
<style>
  body { font: 14px/1.6 Georgia, serif; color: #1c1917; max-width: 720px; margin: 48px auto; padding: 0 24px; }
  header { border-bottom: 3px solid #1c1917; padding-bottom: 18px; margin-bottom: 32px; }
  h1 { font-size: 34px; margin: 0; letter-spacing: -0.5px; }
  .sub { color: #57534e; margin-top: 6px; font-style: italic; }
  h2 { font-size: 13px; letter-spacing: 3px; text-transform: uppercase; color: #78716c; border-bottom: 1px solid #e7e5e4; padding-bottom: 6px; margin: 36px 0 14px; }
  h3 { font-size: 15px; margin: 14px 0 2px; }
  p { margin: 2px 0 10px; }
  .field.locked { border-left: 3px solid #d97706; padding-left: 12px; }
  .badge { font: 700 9px/1 sans-serif; letter-spacing: 1px; color: #d97706; vertical-align: middle; }
  .lens { font: 400 11px/1 sans-serif; color: #a8a29e; }
  .analysis { color: #57534e; font-size: 13px; }
  .manifest { font-size: 13px; }
  footer { margin-top: 48px; padding-top: 12px; border-top: 1px solid #e7e5e4; font-size: 11px; color: #a8a29e; font-family: sans-serif; }
  @media print { body { margin: 0 auto; } }
</style></head><body>
<header>
  <h1>${esc(brand.name)}</h1>
  <p class="sub">${esc(brand.description)}</p>
  ${brand.heroEssence ? `<p class="sub">Hero truth: ${esc(brand.heroEssence)}</p>` : ''}
</header>
${axisBlock('narrative', 'Narrative — what we say')}
${axisBlock('sensation', 'Sensation — what it feels like')}
${axisBlock('viewing', 'Viewing — how it is looked at')}
${conceptsBlock}
<footer>Generated by Praxis · ${new Date().toISOString().slice(0, 10)} · print this page to PDF for distribution</footer>
</body></html>`;

    const blob = new Blob([html], { type: 'text/html' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `${brand.id}-brand-book.html`;
    a.click();
    URL.revokeObjectURL(a.href);
}
