import { CSSProperties } from 'react';

/** Minimal shared inline styles — no CSS framework in 2.0 yet. */
export const S: Record<string, CSSProperties> = {
    page: {
        fontFamily: 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        height: '100vh',
        display: 'flex',
        overflow: 'hidden',
        background: 'radial-gradient(circle at 18% 0%, #313846 0, #151820 36%, #0e1015 100%)',
        color: '#18181b',
    },
    sidebar: {
        width: 232,
        flexShrink: 0,
        display: 'flex',
        flexDirection: 'column',
        gap: 14,
        padding: 14,
        borderRight: '1px solid rgba(255,255,255,0.12)',
        background: 'rgba(17, 19, 24, 0.68)',
        backdropFilter: 'blur(22px) saturate(1.35)',
        WebkitBackdropFilter: 'blur(22px) saturate(1.35)',
        color: '#f4f4f5',
        boxSizing: 'border-box',
    },
    brandBlock: { display: 'flex', flexDirection: 'column', gap: 3, padding: '6px 6px 2px' },
    brand: { fontWeight: 750, fontSize: 15, letterSpacing: 0, color: '#fafafa' },
    brandSubtle: { fontSize: 11, color: '#8b929f' },
    nav: { display: 'flex', flexDirection: 'column', gap: 3 },
    tab: {
        minHeight: 36,
        width: '100%',
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        justifyContent: 'flex-start',
        padding: '0 10px',
        borderRadius: 8,
        border: '1px solid transparent',
        background: 'transparent',
        fontSize: 13,
        fontWeight: 650,
        color: '#b8bec8',
        cursor: 'pointer',
        textAlign: 'left',
    },
    tabActive: { background: 'rgba(255,255,255,0.12)', color: '#fff', borderColor: 'rgba(255,255,255,0.13)', boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.08)' },
    shell: { flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', background: 'rgba(245,246,248,0.82)', backdropFilter: 'blur(18px)', WebkitBackdropFilter: 'blur(18px)' },
    topbar: {
        minHeight: 48,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
        padding: '0 20px',
        borderBottom: '1px solid #e2e5ea',
        background: 'rgba(251,251,252,0.72)',
        backdropFilter: 'blur(18px) saturate(1.25)',
        WebkitBackdropFilter: 'blur(18px) saturate(1.25)',
        boxSizing: 'border-box',
    },
    main: { flex: 1, overflow: 'auto', background: 'linear-gradient(180deg, rgba(255,255,255,0.62), rgba(245,246,248,0.92))' },
    label: { fontSize: 10, fontWeight: 750, letterSpacing: 0.8, textTransform: 'uppercase' as const, color: '#7b8190' },
    chip: {
        minHeight: 30,
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        padding: '0 11px',
        borderRadius: 8,
        border: '1px solid #d9dde4',
        background: 'rgba(255,255,255,0.72)',
        backdropFilter: 'blur(12px) saturate(1.15)',
        WebkitBackdropFilter: 'blur(12px) saturate(1.15)',
        fontSize: 12,
        fontWeight: 650,
        color: '#4c525f',
        cursor: 'pointer',
        boxSizing: 'border-box',
    },
    chipOn: { background: 'rgba(32,36,44,0.92)', color: '#fff', borderColor: 'rgba(32,36,44,0.92)' },
    card: {
        background: 'rgba(255,255,255,0.72)',
        border: '1px solid rgba(218,223,231,0.78)',
        borderRadius: 8,
        padding: 16,
        boxShadow: '0 10px 28px rgba(15, 17, 21, 0.06), inset 0 1px 0 rgba(255,255,255,0.65)',
        backdropFilter: 'blur(16px) saturate(1.18)',
        WebkitBackdropFilter: 'blur(16px) saturate(1.18)',
    },
    btn: {
        minHeight: 34,
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        padding: '0 14px',
        borderRadius: 8,
        border: '1px solid #20242c',
        background: 'rgba(32,36,44,0.94)',
        color: '#fff',
        fontSize: 12.5,
        fontWeight: 700,
        cursor: 'pointer',
        boxSizing: 'border-box',
        whiteSpace: 'nowrap',
    },
    btnGhost: {
        minHeight: 32,
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        padding: '0 11px',
        borderRadius: 8,
        border: '1px solid #d9dde4',
        background: 'rgba(255,255,255,0.68)',
        backdropFilter: 'blur(10px) saturate(1.12)',
        WebkitBackdropFilter: 'blur(10px) saturate(1.12)',
        fontSize: 12,
        fontWeight: 650,
        color: '#4c525f',
        cursor: 'pointer',
        boxSizing: 'border-box',
        whiteSpace: 'nowrap',
    },
    input: {
        minHeight: 34,
        border: '1px solid #d9dde4',
        borderRadius: 8,
        padding: '0 10px',
        fontSize: 13,
        outline: 'none',
        background: 'rgba(255,255,255,0.78)',
        color: '#18181b',
        boxSizing: 'border-box',
    },
    sidebarSelect: {
        minHeight: 34,
        width: '100%',
        border: '1px solid rgba(255,255,255,0.12)',
        borderRadius: 8,
        padding: '0 10px',
        fontSize: 12.5,
        fontWeight: 650,
        outline: 'none',
        background: 'rgba(255,255,255,0.08)',
        backdropFilter: 'blur(12px)',
        WebkitBackdropFilter: 'blur(12px)',
        color: '#f4f4f5',
        boxSizing: 'border-box',
    },
    err: { background: '#fff1f2', border: '1px solid #fecdd3', color: '#be123c', borderRadius: 8, padding: '10px 14px', fontSize: 12 },
};

export const chip = (on: boolean): CSSProperties => ({ ...S.chip, ...(on ? S.chipOn : {}) });
